// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvw3prhyGK20p2_JShVPUQjJWPuMdmmQ',
    appId: '1:570309084060:web:2ccca2f7816297bcf47e59',
    messagingSenderId: '570309084060',
    projectId: 'shoesphere-71f4d',
    authDomain: 'shoesphere-71f4d.firebaseapp.com',
    storageBucket: 'shoesphere-71f4d.appspot.com',
    measurementId: 'G-GW7TLVFTSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PSdKYLL0sd4RxEXLi9y1JO7ESkBNnh0',
    appId: '1:570309084060:android:c2f272f0bcc2e7e1f47e59',
    messagingSenderId: '570309084060',
    projectId: 'shoesphere-71f4d',
    storageBucket: 'shoesphere-71f4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVFoMUXf-B2hCcxwENoKb3Ck-JjfNqNxg',
    appId: '1:570309084060:ios:5f9c6c54573bb2a9f47e59',
    messagingSenderId: '570309084060',
    projectId: 'shoesphere-71f4d',
    storageBucket: 'shoesphere-71f4d.appspot.com',
    iosBundleId: 'com.example.shoesphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVFoMUXf-B2hCcxwENoKb3Ck-JjfNqNxg',
    appId: '1:570309084060:ios:5f9c6c54573bb2a9f47e59',
    messagingSenderId: '570309084060',
    projectId: 'shoesphere-71f4d',
    storageBucket: 'shoesphere-71f4d.appspot.com',
    iosBundleId: 'com.example.shoesphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnvw3prhyGK20p2_JShVPUQjJWPuMdmmQ',
    appId: '1:570309084060:web:4d4a079e768af1eaf47e59',
    messagingSenderId: '570309084060',
    projectId: 'shoesphere-71f4d',
    authDomain: 'shoesphere-71f4d.firebaseapp.com',
    storageBucket: 'shoesphere-71f4d.appspot.com',
    measurementId: 'G-P6H7PV6TQ3',
  );

}